### PR TITLE
Fix DZT multi-channel import and bad GPS data from SIR-3000

### LINKED ISSUE #661: Importing DZT from SIR3000 results in bad data
Image

I am getting these faulty views with all files I import from our SIR 3000 

`</BinaryData>
        </Process>
    </Macro>
    <DataCollection>
        <system>SIR-30</system>
        <softwareVersion>1.0.0.0</softwareVersion>
        <Ctable>4</Ctable>
        <Xtable>4</Xtable>
        <displayGain>0</displayGain>
    </DataCollection>
</DZX>
`

It's the 4105 Horn Antenna
` <antennaName>4105</antennaName>`

### PR DESCRIPTION
**Pull request by VladislavGroshkov**

### CODE REVIEW

File: src/main/java/com/ugcs/geohammer/format/dzt/DzgFile.java [hunk 1]
```diff
@@ -84,7 +84,7 @@ public void load(File file) throws IOException {
                     record = new Record();
                     records.put(parseIndex(line), record);
                     record.line1 = line;
-                } else if (line.startsWith("$GPGGA")) {
+                } else if (line.startsWith("$GPGGA") || line.startsWith("$GNGGA")) {
```
Comment (episarenko) [inline src/main/java/com/ugcs/geohammer/format/dzt/DzgFile.java:87]: [Optional] We can use nmea parser lib here as it is done in SvlogParser

File: src/main/java/com/ugcs/geohammer/util/Traces.java [hunk 2]
```diff
@@ -58,6 +58,14 @@ public static List<Trace> copy(List<Trace> traces) {
         return copy(traces, null);
     }
 
+    public static void shiftSamples(List<Trace> traces, float delta) {
```
Comment (episarenko) [inline src/main/java/com/ugcs/geohammer/util/Traces.java]: Rename method as it is not a shift but value increment.

File: src/main/java/com/ugcs/geohammer/format/MultiChannelFile.java [hunk 3]
```diff
@@ -0,0 +1,15 @@
+package com.ugcs.geohammer.format;
+
+import java.io.IOException;
+import java.util.List;
+
+public interface MultiChannelFile {
+
+	int numChannel();
```
Comment (episarenko) [inline src/main/java/com/ugcs/geohammer/format/MultiChannelFile.java]: numChannels

File: src/main/java/com/ugcs/geohammer/format/MultiChannelFile.java [hunk 4]
```diff
@@ -0,0 +1,15 @@
...
+
+	List<Channel> getChannels();
```
Comment (episarenko) [inline src/main/java/com/ugcs/geohammer/format/MultiChannelFile.java]: Remove and use getChannel(int channelIndex) instead

File: src/main/java/com/ugcs/geohammer/format/dzt/SampleCodec.java [hunk 5]
```diff
@@ -0,0 +1,50 @@
...
+import java.nio.ByteBuffer;
+import java.util.Map;
+
+interface SampleCodec {
+
+	int read(ByteBuffer buffer);
+
+	void write(ByteBuffer buffer, int value);
+
+	Map<Integer, SampleCodec> CODECS = Map.of(
```
Comment (episarenko) [inline src/main/java/com/ugcs/geohammer/format/dzt/SampleCodec.java:8]: Fix class order

File: src/main/java/com/ugcs/geohammer/format/dzt/DztHeader.java [hunk 6]
```diff
@@ -138,4 +139,9 @@ public class DztHeader {
 	@BaseField(position = 944)
 	byte[] rh_RGPS = new byte[24]; // GPS info 944
 
+	static long getDataPosition(DztHeader firstHeader) {
+		return firstHeader.rh_data < MINHEADSIZE
```
Comment (episarenko) [inline src/main/java/com/ugcs/geohammer/format/dzt/DztHeader.java]: Can we use rh_data of the current channel?

File: src/main/java/com/ugcs/geohammer/format/dzt/DztReader.java [hunk 7]
```diff
@@ -0,0 +1,154 @@
...
+import org.slf4j.LoggerFactory;
+
+class DztReader {
+
+	private static final Logger log = LoggerFactory.getLogger(DztReader.class);
+
+	List<DztChannel> read(File file, DzgFile dzg) throws IOException {
+		try (SeekableByteChannel channel = Files.newByteChannel(file.toPath(), StandardOpenOption.READ)) {
+			List<DztHeader> headers = readHeaders(channel);
+			logHeader(headers.getFirst());
```
Comment (episarenko) [inline src/main/java/com/ugcs/geohammer/format/dzt/DztReader.java]: Log all headers. Check list size

File: src/main/java/com/ugcs/geohammer/format/dzt/DztReader.java [hunk 8]
```diff
@@ -0,0 +1,154 @@
...
+		List<DztHeader> headers = new ArrayList<>(numChannels);
+		headers.add(firstHeader);
+		for (int i = 1; i < numChannels; i++) {
+			headers.add(readHeaderAt(channel, byteMapper, (long) i * DztHeader.MINHEADSIZE));
+		}
+		return headers;
+	}
+
+	private DztHeader readHeaderAt(SeekableByteChannel channel,
+			ObjectByteMapper byteMapper, long position) throws IOException {
```
Comment (episarenko) [inline src/main/java/com/ugcs/geohammer/format/dzt/DztReader.java]: Do not pass ObjectByteMapper as argument, make ObjectByteMapper.readObject static.

File: src/main/java/com/ugcs/geohammer/format/dzt/SampleCodec.java [hunk 9]
```diff
@@ -0,0 +1,50 @@
...
+			16, new Sample16Bit(),
+			32, new Sample32Bit());
+
+	static SampleCodec forBitDepth(int bits) {
+		return CODECS.get(bits);
+	}
+
+	static int traceBufferSize(int bits, int numSamples) {
+		int bytesPerSample = bits / 8;
```
Comment (episarenko) [inline src/main/java/com/ugcs/geohammer/format/dzt/SampleCodec.java]: bits >> 3 may be little faster than division

File: src/main/java/com/ugcs/geohammer/format/dzt/DztChannel.java [hunk 10]
```diff
@@ -0,0 +1,43 @@
...
+
+	private final DztHeader header;
+	private final MinMaxAvg sampleAverage;
+	private final List<Trace> traces;
+
+	DztChannel(int index, String name, DztHeader header,
+			List<Trace> traces, MinMaxAvg sampleAverage) {
+		super(index, name);
+		this.header = header;
+		this.traces = traces;
```
Comment (episarenko) [inline src/main/java/com/ugcs/geohammer/format/dzt/DztChannel.java]: traces = new ArrayList(numTraces from headers); // init

File: src/main/java/com/ugcs/geohammer/format/dzt/DztReader.java [hunk 11]
```diff
@@ -0,0 +1,154 @@
...
+			List<ChannelDecoder> decoders, DzgFile dzg) throws IOException {
+
+		int numChannels = decoders.size();
+
+		int globalIndex = 0;
+		while (channel.position() < channel.size()) {
+			if (Thread.currentThread().isInterrupted()) {
+				throw new CancellationException();
+			}
+			int ch = globalIndex % numChannels;
```
Comment (episarenko) [inline src/main/java/com/ugcs/geohammer/format/dzt/DztReader.java]: rename ch to channelIndex

Comment (episarenko) [reply src/main/java/com/ugcs/geohammer/format/dzt/DztReader.java]: for (int traceIndex = 0; traceIndex < numTraces; traceIndex++) {
  for (int channelIndex = 0; channelIndex < numChannels; channelIndex++) {
  }
}

File: src/main/java/com/ugcs/geohammer/format/dzt/DztFile.java [hunk 12]
```diff
@@ -300,21 +149,43 @@ private List<DzgFile.IndexMapping> buildDzgMappings(IndexRange range) {
...
 
 		copy.setFile(getFile());
 		copy.setUnsaved(isUnsaved());
 
 		List<Trace> tracesCopy = Traces.copy(traces);
 		List<BaseObject> elementsCopy = AuxElements.copy(getAuxElements());
 
+		copy.channels = new ArrayList<>(this.channels.size());
+		for (int i = 0; i < this.channels.size(); i++) {
+			DztChannel src = this.channels.get(i);
```
Comment (episarenko) [inline src/main/java/com/ugcs/geohammer/format/dzt/DztFile.java]: Always copy all channels
